[workspace]
members = [
  "black_marlin",
  "black_marlin-compiler",
  "black_marlin-macros",
  "black_marlin-tests/integration-tests"
]
exclude = [
  "black_marlin-tests/fuzzing-tests",
  "examples"
]
