[package]
name = "black_marlin-examples"
version = "0.3.3"
authors = ["Ryohei Machida <orcinus4627@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
actix-web = { version = "2.0.0", default-features = false }
actix-rt = "1.1.1"
black_marlin = { path = "../black_marlin" }
black_marlin-macros = { path = "../black_marlin-macros" }

[[bin]]
name = "simple"
path = "simple.rs"
test = false

[[bin]]
name = "include"
path = "include.rs"
test = false

[[bin]]
name = "actix"
path = "actix.rs"
test = false
