[package]
name = "black_marlin-compiler"
version = "0.3.4"
authors = ["Ryohei Machida <orcinus4627@gmail.com>"]
description = "Simple, small, and extremely fast template engine for Rust"
homepage = "https://github.com/vthg2themax/black_marlin"
repository = "https://github.com/vthg2themax/black_marlin"
readme = "../README.md"
keywords = ["markup", "template", "html"]
categories = ["template-engine"]
license = "MIT"
workspace = ".."
edition = "2018"

[lib]
name = "black_marlin_compiler"
doctest = false

[features]
default = ["config"]
procmacro = []
config = ["yaml-rust"]

[dependencies]
memchr = "2.4.1"
quote = { version = "1.0.14", default-features = false }
yaml-rust = { version = "0.4.5", optional = true }
home = "0.5.3"
filetime = "0.2.15"

[dependencies.syn]
version = "1.0.85"
default-features = false
features = ["parsing", "full", "visit-mut", "printing"]

[dependencies.proc-macro2]
version = ">=1.0.11, <=1.0.36"
default-features = false
features = ["span-locations"]

[dev-dependencies]
pretty_assertions = "1.0.0"